### ISSUE TITLE
 Leopard Issue: Web Demo not start with error 'pv_leopard_init' failed with status INVALID_ARGUMENT

### ISSUE THREAD

**Issue by opkm** [Picovoice/leopard#107]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Steps to reproduce the behaviour

(Include enough details so that the issue can be reproduced independently.)

**Comment by ksyeo1010** [comment]
We have released the official web package: https://github.com/Picovoice/leopard/pull/126.
