### ISSUE TITLE
iOS and android libraries

### ISSUE THREAD

**Issue by engramyosama6** [Picovoice/leopard#12]
Hey guys I have previously asked about flutter plug-in and I know it doesn't exist.

But what about the iOS and android libraries? How can I access it?

**Comment by engramyosama6** [comment]
Hey guys, could you answer me please :)

**Comment by kenarsa** [comment]
Cheetah and Leopard are available on iOS and Android but at this point only for Alpha customers. We do have plans to release them via GitHub which would make them available to the wider community and startups by the end of this year.
