### ISSUE TITLE
pvLeopard not exported by package leopard

### ISSUE THREAD

**Issue by kercre123** [Picovoice/leopard#128]
**Is your feature request related to a problem? Please describe.**

I am using Golang 1.19 and am trying to define a Leopard object. In older versions of Leopard, I could define it like

`var leopardInstance leopard.Leopard`

But now, the name has changed to pvLeopard (starting with a lowercase character) rather than Leopard (starting with a capital character), so it gives the error shown in the title.

**Describe the solution you'd like**

I would like pvLeopard to start with a capital letter so it is exported, like `leopard.PvLeopard` or `leopard.Leopard` rather than `leopard.pvLeopard`.

**Additional context**
The intended use is like this:

leopardInstance := leopard.NewLeopard("key")
(do stuff with leopardInstance)

But my use-case involves having multiple Leopard processes ready to be used at any time, and there isn't enough time to initiate a process each time a request comes in. This is what my code was like before this change

var leopardSTTArray []leopard.Leopard
for i := 0; i < picovoiceInstances; i++ {
	fmt.Println("Initializing Picovoice Instance " + strconv.Itoa(i))
	leopardSTTArray = append(leopardSTTArray, leopard.NewLeopard(picovoiceKey))
	leopardSTTArray[i].Init()
}

**Comment by mrrostam** [comment]
Thanks for reporting this. 

A new Go package is released, in which `leopard.pvLeopard` is renamed as `leopard.Leopard`. Please update the leopard module to `v1.1.1` to get new changes.

**Comment by kercre123** [comment]
Thank you! Everything is now working how I want.
