### ISSUE TITLE
Leopard Issue: Golang - Panic when no text was transcribed

### ISSUE THREAD

**Issue by kercre123** [Picovoice/leopard#133]
Go 1.18.2, v1.1.1 leopard bindings

### Expected behaviour

When the Process function gets called and it is given audio data with no transcribe-able voice data, it should return a blank string or something to indicate there was no text transcribed

### Actual behaviour

A panic happens and the program crashes, here is the trace [https://pastebin.com/raw/PKzqVmnj](https://pastebin.com/raw/PKzqVmnj)

A defer-recover function could be used to prevent a crash, but that is not ideal.

### Steps to reproduce the behaviour

Call the Process function with audio data that does not have any transcribe-able voice in it.

**Comment by ErisMik** [comment]
I was able to reproduce and fix the issue, thank you for the report! Please try with the Go Leopard binding `v1.1.2`, it should now not panic and just return an empty string as the `transcript`. Keep in mind `words` will be `nil` in this instance.

Closing as fixed, please feel free to open another issue if you run into any more issues, or comment here if this error persists.
