### ISSUE TITLE
Leopard Documentation Issue: Need for specific GlibC version on Raspberry

### ISSUE THREAD

**Issue by TimWolz** [Picovoice/leopard#141]
### What is the URL of the doc?
https://picovoice.ai/docs/quick-start/leopard-python/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
I tried to use leopard on my Raspberry 4 with Raspian Buster. Unfortunately, I get the following error that I don't have the correct glibc version `/lib/arm-linux-gnueabihf/libm.so.6: version 'GLIBC_2.29' not found`. In the documentation, I can't find any information about the need of a specific version. From what I read it's discouraged to only upgrade glibc. So does one need the latest Raspberry OS for leopard to work?

Cheetah and porcupine work flawlessly. Really great software. Thanks so much for developing it and making it available for personal users :)

**Comment by mrrostam** [comment]
Hi @TimWolz 

Thanks for reporting this. We only support the latest official release of Raspbian, which is "bullseye" at the moment, and we will update all our docs to mention it explicitly.

However, you said you could run Cheetah on the same device without any issues, which is odd as both Leopard and Cheetah require Glibc 2.29.

Are you using the latest Cheetah Python package?

**Comment by TimWolz** [comment]
Hi @mrrostam,

Thanks for the quick reply and the info. Then I will update my OS accordingly :) 

Sorry, I actually meant Rhino (using version 2.1.2). Got confused with all the animals :D
