### ISSUE TITLE
LeopardIOError not otherwise specified 

### ISSUE THREAD

**Issue by drobwolf** [Picovoice/leopard#142]
On Ubuntu 20.04, with version 1.1.2, installed via pip3, when calling the process_file method whether passing absolute or relative paths I get the following error:

“LeopardIOError:”

I cannot figure this out because when this error is raised in the code it appears to always have additional verbiage (“cannot find the [audio/model/etc]”). My error message does not further specify what the IO error is. The sample rate of the file is 48000, but this is greater than the sample rate param (which is 16000), and this should be supported by the process_file method based on the comments

**Comment by kenarsa** [comment]
If you can share the audio file you are trying to transcribe somehow and the command you are using then we can help. Otherwise, it is impossible for us to recreate this issue and find a possible solution.

**Comment by drobwolf** [comment]
https://www.dropbox.com/s/nhydwkj29wl0y1g/Skull_Base_and_Sinonasal_Tumors.m4a?dl=0

import pvleopard

leopard = pvleopard.create(access_key='${ACCESS_KEY}')

transcript, words = leopard.process_file('${AUDIO_PATH}')

**Comment by kenarsa** [comment]
@drobwolf, thank you! I managed to reproduce it. I am not sure what is the root cause but something is either off about the audio file or Leopard has a bug. Unsure at this point but we will investigate.

In the meantime, a workaround for you is to convert your file to a different format and that will work. I just converted it to WAV using `Audacity` and Leopard transcribed it successfully. You can use `FFmpeg` as well.

**Comment by drobwolf** [comment]
Ah beautiful, thanks!!

**Comment by ErisMik** [comment]
@drobwolf Thank you for the report. We've identified the issue and are working on a fix. It should be included in the next version of Leopard. For now, you'll have to continue using @kenarsa's workaround of re-encoding to a different supported format.

**Comment by drobwolf** [comment]
Fantastic!! Thanks again

**Comment by laves** [comment]
@drobwolf - we've addressed this issue in the latest Leopard release ([v1.2](https://github.com/Picovoice/leopard/releases/tag/v1.2)). Try the new version and feel free to open a new issue if you have any problems. Thank you for reporting.
