### ISSUE TITLE
Picovoice Documentation Issue (/docs/quick-start/leopard-linux/)

### ISSUE THREAD

**Issue by kcoul** [Picovoice/leopard#170]
### What is the URL of the doc?
https://picovoice.ai/docs/quick-start/leopard-linux/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
Links to C API and dot-NET API are reversed

**Comment by mrrostam** [comment]
thanks for the report. We've fixed the document and the change should be live now.
