### ISSUE TITLE
Add flutter macos plugin

### ISSUE THREAD

**Issue by bakua** [Picovoice/leopard#177]
Hello,

I can see there is Flutter Android/iOS compatible plugin. We are building a MacOS commercial product in Flutter. Would be feasible for you to add MacOS support to your Flutter library, please?

Thank you,
Jakub

**Comment by bakua** [comment]
Hmm, this might be a problem though https://github.com/flutter/flutter/issues/47681

**Comment by kenarsa** [comment]
@bakua, this is not part of our immediate roadmap. However, if you like, you can contribute, and we will be happy to look into your PR.

Alternatively, if you are building a commercial product and ready to engage formally, you can [contact sales](https://picovoice.ai/pricing/) and ask for this support via an enterprise package.
