### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ricardoborges** [Picovoice/leopard#181]
I don't understand the free version, can I use it in a web app, no matter how users will access the web app?

**Comment by mrrostam** [comment]
Yes! you can use your free-tier AccessKey in a web app, however, whenever a user make use of your web app, it will count against your "Monthly Usage Hours", which should be 100 hours. The free-tier primarily is designed for hobbyists who need Leopard for their personal projects or developers who want to give Leopard a quick try and see if it is useful for their goals
