### ISSUE TITLE
[Error] license file belongs to a different version of the library

### ISSUE THREAD

**Issue by hikaru-coder** [Picovoice/leopard#2]
Hi Sir,

I am using Ubuntu 14.04 LTS to try your demo. I had complied using gcc -I include/ -O3 demo/c/leopard_demo.c -ldl -o leopard_demo. However, I faced problem when I tried to run the following:
./leopard_demo \
./lib/linux/x86_64/libpv_leopard.so \
./lib/common/acoustic_model.pv \
./lib/common/language_model.pv \
./resources/license/leopard_eval_linux.lic \
./resources/audio_samples/test.wav

It gave me an error of the following:

**[Error] license file belongs to a different version of the library**

Is there anyway to resolve this?

**Comment by kenarsa** [comment]
on Ubuntu 18.04 this runs correctly. Is this an x86_64 machine?

**Comment by hikaru-coder** [comment]
Yes. It is an x86_64 machine.

**Comment by kenarsa** [comment]
We haven't tested it on 14.04 but on 16.04 and 18.04 it works. suggest upgrading OS.
