### ISSUE TITLE
Leopard Issue: Unable to use Android demo because of "initalization failed" error message

### ISSUE THREAD

**Issue by benkeane** [Picovoice/leopard#219]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
To be able to use the Android demo with my AccessKey from the console.  

### Actual behaviour
I have used the same AccessKey in the python demo and it works, but when I use that AccessKey in the Android Demo I get:
Initialisation Failed.
Ensure your AccessKey 'removed for security reasons' is valid.

i have checked the app has access to the internet and it says its connected by adding the following code to your demo:
ConnectivityManager cm = (ConnectivityManager)getApplicationContext().getSystemService(Context.CONNECTIVITY_SERVICE);
        NetworkInfo nInfo = cm.getActiveNetworkInfo();
        boolean connected = nInfo != null && nInfo.isAvailable() && nInfo.isConnected();
        if (connected) Log.d("ben", "connected = yes");
        else Log.d("ben", "connected = no");

### Steps to reproduce the behaviour
Android 11 and Android 13 phones
Use my access key with the Android demo app. I have submitted this error under a personal account, but if you search my name in your console you'll see I have an account with my work email that I didn't want to share online. 

(Include enough details so that the issue can be reproduced independently.)

**Comment by laves** [comment]
Thanks for the report! I've patched it with https://github.com/Picovoice/leopard/pull/220. Pull latest to confirm the fix.
