### ISSUE TITLE
Leopard Documentation Issue: Cannot find the param.json and model files specified in Leopard flutter demo

### ISSUE THREAD

**Issue by Usama9999** [Picovoice/leopard#235]

**Comment by ksyeo1010** [comment]
You should run `dart scripts/prepare_demo.dart ${LANGUAGE}` replacing `${LANGUAGE}` with the language of your choice as instructed in the readme https://github.com/Picovoice/leopard/blob/master/demo/flutter/README.md before running the demo.

**Comment by Usama9999** [comment]
dart scripts/prepare_demo.dart
Unhandled exception:
PathNotFoundException: Cannot open file, path =
'/E:/android.appliance-speech-to-text-picovoice/scripts\..\..\..\resources\test\test_data.json'
(OS Error: The system cannot find the path specified.
, errno = 3)
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
<asynchronous suspension>
#2      _File.readAsString (dart:io/file_impl.dart:621:18)
<asynchronous suspension>
#3      readJsonFile
(file:///E:/android.appliance-speech-to-text-picovoice/scripts/prepare_demo.dart:16:15)
<asynchronous suspension>
#4      main
(file:///E:/android.appliance-speech-to-text-picovoice/scripts/prepare_demo.dart:22:18)
<asynchronous suspension>

**Comment by ksyeo1010** [comment]
did you just copy out the flutter demo? clone the repo and try it there `git clone --recurse-submodules https://github.com/Picovoice/leopard.git`
