### ISSUE TITLE
Russian language support

### ISSUE THREAD

**Issue by shvchk** [Picovoice/leopard#255]
**Is your feature request related to a problem? Please describe.**
Leopard doesn't support Russian language

**Describe the solution you'd like**
Leopard being able to recognize Russian

**Additional context**
I know additional languages support is planned, but there is no clear way to be notified when particular language is available. If that's ok, maybe this FR could be used for that: those interested could subscribe, and when support for Russian language lands, this FR gets closed, and all subscribers are automatically notified by GitHub : )

And thank you for your work! 🤘

**Comment by ErisMik** [comment]
Hi @shvchk, unfortunately we prefer not to keep issues open for thing like this as it interferes with our project management. If you want to be notified, you can sign up for our newsletter (by going to https://picovoice.ai/ and scrolling down to the footer), and when Russian leopard is available we will send out a notification.
