### ISSUE TITLE
Automatic punctuation in "words" list 

### ISSUE THREAD

**Issue by TheAnton1** [Picovoice/leopard#265]
**Is your feature request related to a problem? Please describe.**
I am trying to make subtitles to videos with leopard's function "leopard.process_file()"  and I want to do it with punctuation in it. But enable_automatic_punctuation=True works only on "transcript" string but not on list of words and because of that there's no punctuation in subtitles. I am using Python.

**Describe the solution you'd like**
If enable_automatic_punctuation is True, then punctuation is on not only in transcript, but in words as well.

**Describe alternatives you've considered**
I would like to see one more flag like "enable_punctuation_in_words" that enables to add punctuation the same way as in transcript string.

**Additional context**
![image](https://github.com/Picovoice/leopard/assets/71664787/c65d2a54-0c83-4bcd-a329-67bbae3e8674)
![image](https://github.com/Picovoice/leopard/assets/71664787/aea21935-a760-4e71-a248-b10278df85b1)
As you can see on that images, there's the end of the sentence in transcript (and the dot as well there), but there's no dot in words.
And also i have a question. what punctuation leopard can mark in text? I didnt find this in documentation, sorry.
Thank you very much!

**Comment by kenarsa** [comment]
@TheAnton1, thanks for the issue. You are correct. The punctuation is only in the transcript. Using simple logic, you can also transplant the punctuation from the transcript to the words. Unfortunately, I don't think this is a feature we can prioritize at this point.
