### ISSUE TITLE
Leopard Issue: Python library not working - GLIBC_2.29 not found 

### ISSUE THREAD

**Issue by Patrick257** [Picovoice/leopard#273]
### Expected behaviour

pvleopard.create(...) should work similiar to the other constructors e.g. pvrhino.create(...) and pvporcupine.create(...).

### Actual behaviour

The constructors for pvrhino.create(...) and pvporcupine.create(...), which I have been using for several months now, are working as expected when used in Python 3.7.3 on Raspian (Buster).

The constructor pvleopard.create(...) fails:

>     self._leopard = pvleopard.create(access_key=ACCESS_KEY, model_path=LEOPARD_MODEL_PATH)
>   File "/home/patrick/.local/lib/python3.7/site-packages/pvleopard/_factory.py", line 44, in create
>     enable_automatic_punctuation=enable_automatic_punctuation)
>   File "/home/patrick/.local/lib/python3.7/site-packages/pvleopard/_leopard.py", line 148, in __init__
>     library = cdll.LoadLibrary(library_path)
>   File "/usr/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
>     return self._dlltype(name)
>   File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /home/patrick/.local/lib/python3.7/site-packages/pvleopard/lib/raspberry-pi/cortex-a72/libpv_leopard.so)

When I try to manually upgrade GLIBC, I get:

> sudo apt-get install libc6
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> libc6 is already the newest version (2.28-10+rpt2+rpi1+deb10u2).
> The following package was automatically installed and is no longer required:
>   libva-wayland2
> Use 'sudo apt autoremove' to remove it.
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Is it really the case that Leopard - unlike the other libraries - needs GLIBC 2.29?

**Comment by kenarsa** [comment]
`Leopard,` as it stands, has a dependency on that version of `glibc.` Could you upgrade to a newer version of the OS? We plan to remove this dependency in the next release (this year), but I can't commit to a timeline.

**Comment by Patrick257** [comment]
Thanks for the feedback! Indeed I can't currently upgrade to a newer version of the OS due to some other dependencies in my project, so I may have to wait. Does the same limitation apply to Cheetah as well?
