### ISSUE TITLE
Are there any tools to recognize only digits in popular languages?

### ISSUE THREAD

**Issue by denizsincar29** [Picovoice/leopard#289]
Hello. Are there any tools, maybe by picovoice or other, that can recognize digits in many languages at once?
I want to be able to quickly transform all digits heard into, well, string of numbers. In many popular languages like english, italian, spanish, russian, german...
Thank you.

**Comment by ErisMik** [comment]
Unfortunately I don't know of any tools off the top of my head that meet those exact specifications, but closely related is our [Rhino Speech-To-Intent Engine](https://github.com/Picovoice/rhino) which has built-ins for digits (transforming them into a numerical representation) and supports a wide variety of languages. You'd have to run multiple instances, one for each language you want to support.

If this is for a commercial application you can always reach out to us at  [hello@picovoice.ai](mailto:hello@picovoice.ai) and we may be able to assist.

**Comment by denizsincar29** [comment]
nope, that uncommercial. Just for me, friends...
