### ISSUE TITLE
Leopard Issue: Android Build Failed | JAVA Version Clash

### ISSUE THREAD

**Issue by rahulkumarmbd** [Picovoice/leopard#306]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
Local system has JAVA 17 version installed. There is some clash happening between the Local java version and the java version used in the android demo.

### Actual behaviour
<img width="1539" alt="image" src="https://github.com/Picovoice/leopard/assets/87120020/4f5dbef7-6d85-4696-942e-a6a4e24de240">

<img width="886" alt="image" src="https://github.com/Picovoice/leopard/assets/87120020/bbead22f-de82-4703-8de6-88934d446f42">

### Steps to reproduce the behaviour
Following the steps in the document, Run -> npm run android-run en , command to view the issue. Expecting to build successfully. without version clashes. 

(Include enough details so that the issue can be reproduced independently.)

**Comment by laves** [comment]
Java 11 should work - we will be reviewing our Java support soon and will attempt to support Java 17+ across all related SDKs

**Comment by laves** [comment]
Closed due to inactivity
