### ISSUE TITLE
Leopard Issue: An error occurred while creating video: Unsupported CPU: `0x000`

### ISSUE THREAD

**Issue by sentient-22** [Picovoice/leopard#339]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
<img width="919" alt="image" src="https://github.com/Picovoice/leopard/assets/30064883/c0b7c08f-1c54-4ad6-b20b-a3b0441c9ec0">

### Actual behaviour
<img width="567" alt="image" src="https://github.com/Picovoice/leopard/assets/30064883/8ab71e39-dd55-488d-b967-887fc4c5c222">

### Steps to reproduce the behaviour
>>> pvleopard.create(access_key=access_key)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/pvleopard/_factory.py", line 42, in create
    library_path = default_library_path('')
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pvleopard/_util.py", line 59, in default_library_path
    linux_machine = _linux_machine()
                    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pvleopard/_util.py", line 45, in _linux_machine
    raise NotImplementedError("Unsupported CPU: `%s`." % cpu_part)
NotImplementedError: Unsupported CPU: `0x000`.
>>>  

(Include enough details so that the issue can be reproduced independently.)

This is running in container docker 
```
FROM python:3.11-slim
# FROM python:3.11-alpine3.18
```
and system arch 
r```
oot@b6136564c5d7:/app# uname -a
Linux b6136564c5d7 5.15.49-linuxkit-pr #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023 aarch64 GNU/Linux
root@b6136564c5d7:/app# uname -am
Linux b6136564c5d7 5.15.49-linuxkit-pr #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023 aarch64 GNU/Linux
root@b6136564c5d7:/app# uname -m
aarch64
root@b6136564c5d7:/app# 
```

**Comment by ErisMik** [comment]
Since I don't have access to your exact setup, can you run this command on your machine and put the output here?
```docker run -it python:3.11-slim cat /proc/cpuinfo```

**Comment by sentient-22** [comment]
apple m2 pro 
Plz provide the pass library path format

**Comment by kenarsa** [comment]
you can find that in the [docs](https://picovoice.ai/docs/api/leopard-python/#pvleopardcreate)

**Comment by sentient-22** [comment]
I am a paid customer of picovoice, I am using to generate srt from video file
Here is instance of google cloud function  as POST api in flask logic 
<img width="1026" alt="image" src="https://github.com/Picovoice/leopard/assets/30064883/f1bfc5f1-76f4-41d8-b797-7ce50c1dcc3e">


However when I am trying to run it on docker as I am getting above error as mentioned above.

**Comment by kenarsa** [comment]
@sentient-22 please reach out to your Picovoice contact to get dedicated engineering support. you can send the link to this issue as the context.
