### ISSUE TITLE
Questions about custom vocabulary and keywords boosting features

### ISSUE THREAD

**Issue by tempo-riz** [Picovoice/leopard#344]
Hello, I have questions about custom vocabulary and keywords boosting features,
Are there limitations ? 

I have 2 use case, one with 1K custom words, the other with 10K, is it still a viable approach accuracy/performance wize or should I consider an alternative/train my own model ?
The same question for Cheetah aswell !

Thanks

**Comment by laves** [comment]
@tempo-riz - sorry for the late response. Yes, Cheetah and Leopard can support on the order of 10K custom words. Performance should not degrade by adding that many custom words. Picovoice Console does limit the input YAML file to 5MB, so your lexicon just needs to fit within that size.

**Comment by tempo-riz** [comment]
Alright good to know thanks :)
