### ISSUE TITLE
Leopard Issue: Why isn't it available through Swift Package Manager on iOS?

### ISSUE THREAD

**Issue by marapz** [Picovoice/leopard#399]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Leopard docs
- [X] I have searched the existing issues for Leopard

### SDK

iOS

### Leopard package version

1.0

### Framework version

Swift 5

### Platform

iOS

### OS/Browser version

iOS 17/18

### Describe the bug

Is it possible to install the library using Swift Package Manager on iOS?

### Steps To Reproduce

.

### Expected Behavior

Install package via SPM as it is the recommended way currently for new projects.

**Comment by ErisMik** [comment]
Thanks for the report. 

We've had a few requests for moving to SPM and we are looking to make the switch. Unfortunately we don't have an estimate when the change will be done. I'll leave this issue up for now and close it when an SPM package for Leopard is available.

**Comment by albho** [comment]
[Leopard (2.0.2)](https://github.com/Picovoice/leopard/tree/master/binding/ios) is out now and has support for SPM.
