### ISSUE TITLE
requires SoundFile-0.10.*

### ISSUE THREAD

**Issue by luto65** [Picovoice/leopard#4]
Dear Picovoice,
please include in documentation that the python test requires installation of SoundFile module

```
python2 -m pip install SoundFile
python3 -m pip install SoundFile

```

**Comment by kenarsa** [comment]
Thanks! Added requirements.txt file

https://github.com/Picovoice/leopard/commit/5396d5dfc8a9041eb4e56cfef3fbefe51b089b3d
