### ISSUE TITLE
picovoice.h uses visibility attribute not available in MSVC

### ISSUE THREAD

**Issue by dubajj** [Picovoice/leopard#50]
currently picovoice.h has

```
#define PV_API __attribute__((visibility("default")))
```

Which does not work with MSVC. This should have an additional switch for MSVC to use either `__declspec(dllimport)` or `__declspec(dllexport)` depending if its for your internal build for the libraries or the consumable client build.

**Comment by kenarsa** [comment]
You need MinGW as stated [here](https://github.com/Picovoice/leopard/tree/master/demo/c#requirements)

**Comment by dubajj** [comment]
sure i read that but with the small change I suggested you don't need MinGW, the dll works fine outside of that context. Its just setting the visibility flag, not changing the functionality of the code at all. Seems kind of arbitrary to limit that compilation?

**Comment by dubajj** [comment]
also your link is for "demo" requirements, but i'm not compiling the demo, this is an in benchmark comparison to your competitors.
