### ISSUE TITLE
Turning words to numbers and avoid saving a file

### ISSUE THREAD

**Issue by Bradams2212** [Picovoice/leopard#85]
For a project, I tried using pvleopard but had to ultimately decide against it. This was because of two issues:

1. It would take the user saying 'forty four' and return the words 'forty four' instead of the number.
2. I could only use it for a limited amount of time or I would have to use speech recognition to save the file and then process the wav file.

I was wondering if there were any ways around these issues. For the second one, I would like to avoid using speech recognition but would need the program to stop listening when the user has stopped talking, not after a set amount of time. Sorry if this isn't the right place for this.

**Comment by kenarsa** [comment]
can you please elaborate on the project and what you are trying to achieve? Then I can help better.

**Comment by kenarsa** [comment]
have you tried Rhino?

**Comment by Bradams2212** [comment]
How does rhino work?

**Comment by Bradams2212** [comment]
If the action is something like check the weather or get my schedule for this day, it can do that? What about more specific commands like raise a frame in tkinter

**Comment by Bradams2212** [comment]
Also, the demo files only show saving the file to a wav. Is there a way around that?

**Comment by Bradams2212** [comment]
I didn't need to with porcupine. If I use a similar method will that work or is porcupine different in that respect

**Comment by Bradams2212** [comment]
I already have preexisting code to take the users voice input and interpret what they want. Would it be possible for rhino to interpret what the user wants to do, convert what they said to a string and then pass that into my pre-existing functions?

**Comment by kenarsa** [comment]
quick re-cap:

1- Leopard does not have the capability to turn written numbers into numeric form (i.e. `seven` to `7`) and there is no immediate plan for it.
2- Rhino has that functionality. You can also mix or match it with Leopard as/if needed.
3- You should look into the header file (binding code) to learn how to use each engine. A demo is just a demo.
