### ISSUE TITLE
Transcripts with Word Alignments

### ISSUE THREAD

**Issue by weisrc** [Picovoice/leopard#92]
Hello,

Is it possible to output the world alignments similar to Mozilla's Deepspeech when using Leopard?

I tried looking around the docs and can't seem to find it. If it is not possible, any suggestions on how I can achieve it using Picovoice.

Thank you!

**Comment by weisrc** [comment]
Can you provide an ETA for this feature to be completed? Thank you!

**Comment by kenarsa** [comment]
not at the moment

**Comment by kenarsa** [comment]
the feature is released in `v1.1`
