### ISSUE TITLE
Request: Cortex-A7 Linux lib

### ISSUE THREAD

**Issue by kercre123** [Picovoice/leopard#95]
I would like to run a golang application on a Qualcomm APQ8009 armv7 CPU which utilizes Leopard. I tried modifying the code a bit to use the android/armeabi-v7a lib but the golang wrappers don't seem to be compatible with it. By default, on an APQ8009 running embedded Linux, I get an error saying "Unsupported CPU: 0xc07". I also have a Banana Pi with a Cortex-A7 processor which I would like to try running this on. Judging by how well Leopard works on old Core 2 Duo processors it seems like it would run well on this too.

**Comment by kercre123** [comment]
I got Rhino working and it fits my needs

**Comment by kercre123** [comment]
Reopening now that I understand better what the issue is. Rhino and Porcupine have cortex-a7 raspberry pi libs which work perfectly on the APQ8009 processor as described in the original issue. Would it be possible to build a cortex-a7 Leopard lib for Raspberry Pi like there is for Rhino and Porcupine? I understand that this request is very specific and I can modify my program to use Rhino, but there are certain parts of it where speech-to-text would be best.

**Comment by kenarsa** [comment]
@kercre123 Unfortunately this is not on the roadmap. If this is for a commercial application and you are at a point to engage formally you can contact the [sales team](https://picovoice.ai/contact/) and they might find a way to accommodate your request as part of the engagement via NRE.
